{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.yukihookapi",
    "module": "yukihook-compiler",
    "version": "1.5.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-compiler-1.5.0-beta.5.jar",
          "url": "yukihook-compiler-1.5.0-beta.5.jar",
          "size": 48323,
          "sha512": "deb12fcda6474538203adc23a483f0edd6b247c6dd32cd539cc2e56a105188d585c29073e69d0462d46d4652d6ee8b402a91a4535a10ee60389393572150e6ef",
          "sha256": "b433b70687d88eed57527b2118b86c03e9ceefca6a0eebea6c6ad48ccb96fbe7",
          "sha1": "d6b487ac8aa56bf1000e56d742119d79fd45a36d",
          "md5": "0712238f237d5358fa8974aeb532fb2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-compiler-1.5.0-beta.5.jar",
          "url": "yukihook-compiler-1.5.0-beta.5.jar",
          "size": 48323,
          "sha512": "deb12fcda6474538203adc23a483f0edd6b247c6dd32cd539cc2e56a105188d585c29073e69d0462d46d4652d6ee8b402a91a4535a10ee60389393572150e6ef",
          "sha256": "b433b70687d88eed57527b2118b86c03e9ceefca6a0eebea6c6ad48ccb96fbe7",
          "sha1": "d6b487ac8aa56bf1000e56d742119d79fd45a36d",
          "md5": "0712238f237d5358fa8974aeb532fb2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yukihook-compiler-1.5.0-beta.5-sources.jar",
          "url": "yukihook-compiler-1.5.0-beta.5-sources.jar",
          "size": 36813,
          "sha512": "ef1b80aeeda7af21b3eb7f4a542d58e9f9ee7d5ccbdd3154d1d1e2debe7b12e85777c48004c5a40b78747d0a5db222150da6ebad643cc813c560f6b76e117980",
          "sha256": "684b959174931a44d3eb9a24b2a5aeaf72b1a11018c7812f250723145b95bf68",
          "sha1": "bb0fd524839163afacf6f1ad1e72ae83ddb9732f",
          "md5": "c88b36a67c630a9c13d73dc564ea3ec0"
        }
      ]
    }
  ]
}
