{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.yukihookapi",
    "module": "yukihook-core",
    "version": "1.5.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-core-1.5.0-beta.5.aar",
          "url": "yukihook-core-1.5.0-beta.5.aar",
          "size": 436047,
          "sha512": "07c7994f94ecc5f93a92c40cd871c5fd4374dd7b96959117270b5f7e29795c0b83ad201ceedeab1563164259c4619c48ecd30271d8188704e9493d5433adf3d8",
          "sha256": "017df524b958b8155051b6189af9972344e70f03955d76d91e47876fa30f5d97",
          "sha1": "8309a29d8abdee2119d626f20c7b76235c92a422",
          "md5": "44ebc46fc7d71417185a732814017112"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lsposed.hiddenapibypass",
          "module": "hiddenapibypass",
          "version": {
            "requires": "6.1"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "android-bom",
          "version": {
            "requires": "1.1.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "ui-extension"
        },
        {
          "group": "com.highcapable.betterandroid",
          "module": "system-extension"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-core-1.5.0-beta.5.aar",
          "url": "yukihook-core-1.5.0-beta.5.aar",
          "size": 436047,
          "sha512": "07c7994f94ecc5f93a92c40cd871c5fd4374dd7b96959117270b5f7e29795c0b83ad201ceedeab1563164259c4619c48ecd30271d8188704e9493d5433adf3d8",
          "sha256": "017df524b958b8155051b6189af9972344e70f03955d76d91e47876fa30f5d97",
          "sha1": "8309a29d8abdee2119d626f20c7b76235c92a422",
          "md5": "44ebc46fc7d71417185a732814017112"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yukihook-core-1.5.0-beta.5-sources.jar",
          "url": "yukihook-core-1.5.0-beta.5-sources.jar",
          "size": 161346,
          "sha512": "becb34076463c68f0df80f9f6303b91faa62cdcd2d862096484df032f9dc1a46cc8ae19cacc875acc759600b3bf08e3e4204463241edb291a83048fff0c7222a",
          "sha256": "a92de51e281f931100bcce0b9d4b7f01a979c027acb9e3e631a0805ac4d96e5a",
          "sha1": "b6689b083142b16f1fca9c6480e16b859c3afc98",
          "md5": "5484f43196558d863862dea43339b60e"
        }
      ]
    }
  ]
}
