{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.yukihookapi",
    "module": "yukihook-runtime-libxposed",
    "version": "1.5.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-runtime-libxposed-1.5.0-beta.5.aar",
          "url": "yukihook-runtime-libxposed-1.5.0-beta.5.aar",
          "size": 78544,
          "sha512": "71df64c16bd7c289315cf017487a1128c32b28a6a684a0b84bb4ca0cc8f334fe8dc3ed11f9bbe81f1c5fac099c09aa4b91d174f36f1d0a05791b6efb6d6d681d",
          "sha256": "e3a2c9b5496b4dc0c84397e415cdf1543584adc82bb8179049e46a5e28b779b0",
          "sha1": "f0c0133f433f3bf4e24003ee2366ccc04a9d0d79",
          "md5": "38b21acbfd9f6f4b2ff997b0c6c5fd29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.libxposed",
          "module": "service",
          "version": {
            "requires": "102.0.0"
          }
        },
        {
          "group": "com.highcapable.yukihookapi",
          "module": "yukihook-core",
          "version": {
            "requires": "1.5.0-beta.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-runtime-libxposed-1.5.0-beta.5.aar",
          "url": "yukihook-runtime-libxposed-1.5.0-beta.5.aar",
          "size": 78544,
          "sha512": "71df64c16bd7c289315cf017487a1128c32b28a6a684a0b84bb4ca0cc8f334fe8dc3ed11f9bbe81f1c5fac099c09aa4b91d174f36f1d0a05791b6efb6d6d681d",
          "sha256": "e3a2c9b5496b4dc0c84397e415cdf1543584adc82bb8179049e46a5e28b779b0",
          "sha1": "f0c0133f433f3bf4e24003ee2366ccc04a9d0d79",
          "md5": "38b21acbfd9f6f4b2ff997b0c6c5fd29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yukihook-runtime-libxposed-1.5.0-beta.5-sources.jar",
          "url": "yukihook-runtime-libxposed-1.5.0-beta.5-sources.jar",
          "size": 27576,
          "sha512": "45b98b23a74ab451614c8474e653a064fde485d3795e329f684d77c9812bd1ea7a7a73c725b19ee67556a5fc8c095ce019b277f38ac2f9730c838cc97aa6019a",
          "sha256": "aa50e5606042511ef759b53527c1dd70246354670d336b4b87845b92bdbde895",
          "sha1": "e70987e6ea3641b79915e504f70d3aad575b1da4",
          "md5": "560791c870b2622d512c0a05385cd8c4"
        }
      ]
    }
  ]
}
