{
  "formatVersion": "1.1",
  "component": {
    "group": "com.highcapable.yukihookapi",
    "module": "yukihook-runtime-xposed82",
    "version": "1.5.0-beta.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-runtime-xposed82-1.5.0-beta.5.aar",
          "url": "yukihook-runtime-xposed82-1.5.0-beta.5.aar",
          "size": 50294,
          "sha512": "4c4849d0ed0508d697a909cc78864532f8020f23b7a8809217964851cfda8cbad83a9224791b715c7bfe5884fed524f403f0a89d1d71c417edc605fc9aa73637",
          "sha256": "58b6c8f1fe7efb2590f1511f8eff9ae154157cde785338a1b034407c01926751",
          "sha1": "a4a8062ab261cd477c40023ea150f7ce1efdd769",
          "md5": "39bbc54d255f3b6f36b99f262b49471d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.highcapable.yukihookapi",
          "module": "yukihook-core",
          "version": {
            "requires": "1.5.0-beta.5"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-bom",
          "version": {
            "requires": "1.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-core"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-android"
        },
        {
          "group": "com.highcapable.kavaref",
          "module": "kavaref-extension"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "yukihook-runtime-xposed82-1.5.0-beta.5.aar",
          "url": "yukihook-runtime-xposed82-1.5.0-beta.5.aar",
          "size": 50294,
          "sha512": "4c4849d0ed0508d697a909cc78864532f8020f23b7a8809217964851cfda8cbad83a9224791b715c7bfe5884fed524f403f0a89d1d71c417edc605fc9aa73637",
          "sha256": "58b6c8f1fe7efb2590f1511f8eff9ae154157cde785338a1b034407c01926751",
          "sha1": "a4a8062ab261cd477c40023ea150f7ce1efdd769",
          "md5": "39bbc54d255f3b6f36b99f262b49471d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yukihook-runtime-xposed82-1.5.0-beta.5-sources.jar",
          "url": "yukihook-runtime-xposed82-1.5.0-beta.5-sources.jar",
          "size": 15645,
          "sha512": "4821cd13b835d744031e4a2aca876e770ed3bbbdffc26516346608daeda0a31db51fa75eed86d640381548c2a5b11746bc12490aeb795f007047c6d263f6340f",
          "sha256": "71abd0de03bbf95917b7bf92068b78369c82ca0333df531f94d5abc178cd4c7d",
          "sha1": "3ca24d17cf690afcf4c2863a120df3f77914b2de",
          "md5": "98d6b920471792d8b2728c950781bd7c"
        }
      ]
    }
  ]
}
